<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function kinerja_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function kinerja_menu() {

	$items['kinerja/edit'] = array (
      'title' => 'Isian Kinerja',
	  'description' => 'Isian Kinerja',
	  //'title callback' => 'kinerja_title_callback',	  
      'page callback' => 'kinerja_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'kinerja_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['kinerjaarsip'] = array (
      'title' => 'Kinerja SKPD',
	  'description' => 'Kinerja SKPD',
	  //'title callback' => 'kinerja_arsip_title_callback',	  
      'page callback' => 'kinerja_arsip_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'kinerja_arsip_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['kinerjaprint'] = array (
      'title' => 'Kinerja SKPD',
	  'description' => 'Kinerja SKPD',
	  //'title callback' => 'kinerja_arsip_title_callback',	  
      'page callback' => 'kinerja_print_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'kinerja_print_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

 
    return $items;
}


